name: Sync ORCID Publications

on:
  schedule:
    - cron: '0 0 * * 1'  # Every Monday at midnight
  workflow_dispatch:    # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install requests

      - name: Fetch ORCID Works JSON
        run: |
          curl https://pub.orcid.org/v3.0/0000-0003-4731-240X/works \
            -H "Accept: application/json" \
            -o orcid_works.json

      - name: Run ORCID Sync Script
        run: |
          python scripts/orcid_sync.py

      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add content/publication/*
          git commit -m "🔄 Update publications from ORCID" || echo "No changes to commit"
          git push
